version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
          working_directory: project
      - run:
          name: yarn build
          command: yarn build
          working_directory: project
workflows:
  version: 2
  build:
    jobs:
      - build
