version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/project/yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - run: yarn build
workflows:
  version: 2
  build:
    jobs:
      - build
